language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm run build

script:
  - zip -rq latest * .*
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: ddweerasiri/ddweerasiri-website
    bucket: ddweerasiri-website-distro-repo
    region: ap-southeast-2
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ddweerasiri-website-distro-repo
    key: latest.zip
    bundle_type: zip
    application: ddweerasiri-website
    deployment_group: ddweerasiri-website-deployment-group
    region: ap-southeast-2
    on: *2
