version: 0.0
os: linux

files:
  - source: ./
    destination: /home/ec2-user/ddweerasiri-website

hooks:
  AfterInstall:
    - location: code-deploy-scripts/after-install.sh
      timeout: 120
      runas: ec2-user

  ApplicationStart:
    - location: code-deploy-scripts/application-start.sh
      timeout: 60
      runas: ec2-user
